ci:
    # pre-commit ci do not install dependencies from setup.py
  skip: [gen-cli-docs, check-mixin-classes, actionlint-docker, check-github-actions]
repos:
- repo: local
  hooks:
  - id: gen-cli-docs
    name: Generate CLI docs
    language: system
    entry: make docs
    pass_filenames: false
- repo: local
  hooks:
  - id: check-mixin-classes
    name: Validate mixins classes
    language: system
    entry: make check-mixins
    pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.6.0'
  hooks:
  - id: check-merge-conflict
    exclude: "rst$"
- repo: https://github.com/asottile/yesqa
  rev: v1.5.0
  hooks:
  - id: yesqa
- repo: https://github.com/PyCQA/isort
  rev: '5.13.2'
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: '24.4.2'
  hooks:
  - id: black
    language_version: python3   # Should be a command that runs python3.6+
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.6.0'
  hooks:
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: check-added-large-files
  - id: end-of-file-fixer
    exclude: "[.]md$"
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    exclude: "[.]md$"
  - id: check-symlinks
  - id: debug-statements
# Another entry is required to apply file-contents-sorter to another file
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.6.0'
  hooks:
  - id: file-contents-sorter
    files: |
      docs/spelling_wordlist.txt|
      .gitignore
# - repo: https://github.com/asottile/pyupgrade
#   rev: 'v2.37.1'
#   hooks:
#   - id: pyupgrade
#     args: ['--py37-plus']
- repo: https://github.com/twisted/towncrier
  rev: 23.11.0  # run 'pre-commit autoupdate' to update
  hooks:
    - id: towncrier-check
- repo: https://github.com/PyCQA/flake8
  rev: '7.1.0'
  hooks:
  - id: flake8
    exclude: "^docs/"
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.1
  hooks:
  - id: actionlint
    args:
    - -ignore
    - 'SC2155:'
    - -ignore
    - 'SC2086:'
    - -ignore
    - 'SC1004:'
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.29.0
  hooks:
  - id: check-github-actions
